### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Jones-S** [Wiejeben/nuxt.js-craft-boilerplate#1]
Hi

I just wanted to get to run your nice boilerplate.
Unfortunately I get this warning when starting nuxt:

>  ERROR  (node:9111) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added. Use emitter.setMaxListeners() to increase limit

Do you know where that could come from?
I really just set things up without any changes.

```
$ npm install
$ npm run tailwind-schema

# generate GraphQLs schema
$ npm run graphql-schema

# generate both GraphQLs schema and Tailwind IDE CSS file
$ npm run schemas

$ npm run dev
```

Also:
I am running things on node `v10.16.0`. There was no .nvmrc file. I hope that should be alright...

**Comment by Wiejeben** [comment]
Yeah I saw this as well but I was unable to traceback the origin. Since everything functioned as usual I didn't think much of it.

I just released version 1.2 with the latest version of Craft and Nuxt.js, the message seems to have disappeared.
